name: GoSubmit

on:
  pull_request:
    branches:
      - main
      - release-*

jobs:
  release:
    name: get var
    runs-on: ubuntu-latest
    steps:
      - name: set release version
        id: vars
        env:
          RELEASE_NAME: ${GITHUB_REF#refs/tags/}
        run: |
          echo "pr_version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "::set-output name=RELEASE_VERSION::${GITHUB_REF#refs/*/}"
      - name: show release version
      env:
      run: |
        echo ${{ env.pr_version }}
        echo ${{ steps.vars.outputs.RELEASE_VERSION }}
        echo $RELEASE_NAME