name: GoSubmit

on:
  push:
    branches:
      - master
      - release-*
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.16'
  GO_REQUIRED_MIN_VERSION: ''
  GOPATH: '/home/runner/work/zhiweiyin318/testAction/go'
  GITHUB_REF: ${{ github.ref }}

defaults:
  run:
    working-directory: go/src/zhiweiyin318/testAction

jobs:
  release:
    name: get var
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/zhiweiyin318/testAction
      - name: setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.10.0
          name: cluster1
      - name: test secret
        run: |
          echo ${{ secrets.IMAGE_PULL_SECRET }} > secret1
          echo ${IMAGE_PULL_SECRET} >> secret2
          cat secret1
          cat secret2
        env:
          IMAGE_PULL_SECRET: ${{ secrets.IMAGE_PULL_SECRET }}       
      - name: test kind
        run: |
          sleep 120
          kubectl get pods --all-namespaces
          docker logs cluster1-control-plane
      - name: set release version
        id: vars
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_REF#refs/*/}
          echo "TGA_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "::set-output name=RELEASE_VERSION::${GITHUB_REF#refs/*/}"
      - name: get release version
        run: |
          echo ${TGA_VERSION}
          echo ${{ steps.vars.outputs.RELEASE_VERSION }}
          echo "# Registration Operator $RELEASE_VERSION" > changelog.md
          echo "See the [CHANGELOG](https://github.com/zhiweiyin318/registration-operator/blob/main/CHANGELOG/CHANGELOG-v0.1.md) for more details." >> changelog.md
      - name: changelog
        run: cat changelog.md
